/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.liferaybotics.service.base;

import com.liferay.liferaybotics.model.SkuInventory;
import com.liferay.liferaybotics.service.SkuInventoryService;
import com.liferay.liferaybotics.service.SkuInventoryServiceUtil;
import com.liferay.liferaybotics.service.persistence.SkuInventoryFinder;
import com.liferay.liferaybotics.service.persistence.SkuInventoryPersistence;
import com.liferay.liferaybotics.service.persistence.SkuSalesFinder;
import com.liferay.liferaybotics.service.persistence.SkuSalesPersistence;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import java.lang.reflect.Field;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the sku inventory remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.liferaybotics.service.impl.SkuInventoryServiceImpl}.
 * </p>
 *
 * @author Peter Richards
 * @see com.liferay.liferaybotics.service.impl.SkuInventoryServiceImpl
 * @generated
 */
public abstract class SkuInventoryServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, SkuInventoryService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>SkuInventoryService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>SkuInventoryServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		_setServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			SkuInventoryService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		skuInventoryService = (SkuInventoryService)aopProxy;

		_setServiceUtilService(skuInventoryService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return SkuInventoryService.class.getName();
	}

	protected Class<?> getModelClass() {
		return SkuInventory.class;
	}

	protected String getModelClassName() {
		return SkuInventory.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = skuInventoryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		SkuInventoryService skuInventoryService) {

		try {
			Field field = SkuInventoryServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, skuInventoryService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected com.liferay.liferaybotics.service.SkuInventoryLocalService
		skuInventoryLocalService;

	protected SkuInventoryService skuInventoryService;

	@Reference
	protected SkuInventoryPersistence skuInventoryPersistence;

	@Reference
	protected SkuInventoryFinder skuInventoryFinder;

	@Reference
	protected SkuSalesPersistence skuSalesPersistence;

	@Reference
	protected SkuSalesFinder skuSalesFinder;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

}