/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.liferaybotics.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SkuSales service. Represents a row in the &quot;Liferaybotics_SkuSales&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.liferaybotics.model.impl.SkuSalesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.liferaybotics.model.impl.SkuSalesImpl</code>.
 * </p>
 *
 * @author Peter Richards
 * @see SkuSales
 * @generated
 */
@ProviderType
public interface SkuSalesModel extends BaseModel<SkuSales>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sku sales model instance should use the {@link SkuSales} interface instead.
	 */

	/**
	 * Returns the primary key of this sku sales.
	 *
	 * @return the primary key of this sku sales
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this sku sales.
	 *
	 * @param primaryKey the primary key of this sku sales
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the sku of this sku sales.
	 *
	 * @return the sku of this sku sales
	 */
	@AutoEscape
	public String getSku();

	/**
	 * Sets the sku of this sku sales.
	 *
	 * @param sku the sku of this sku sales
	 */
	public void setSku(String sku);

	/**
	 * Returns the group ID of this sku sales.
	 *
	 * @return the group ID of this sku sales
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this sku sales.
	 *
	 * @param groupId the group ID of this sku sales
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this sku sales.
	 *
	 * @return the company ID of this sku sales
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this sku sales.
	 *
	 * @param companyId the company ID of this sku sales
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the quantity sold of this sku sales.
	 *
	 * @return the quantity sold of this sku sales
	 */
	public int getQuantitySold();

	/**
	 * Sets the quantity sold of this sku sales.
	 *
	 * @param quantitySold the quantity sold of this sku sales
	 */
	public void setQuantitySold(int quantitySold);

}