/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.liferaybotics.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SkuInventory service. Represents a row in the &quot;Liferaybotics_SkuInventory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.liferaybotics.model.impl.SkuInventoryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.liferaybotics.model.impl.SkuInventoryImpl</code>.
 * </p>
 *
 * @author Peter Richards
 * @see SkuInventory
 * @generated
 */
@ProviderType
public interface SkuInventoryModel
	extends BaseModel<SkuInventory>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sku inventory model instance should use the {@link SkuInventory} interface instead.
	 */

	/**
	 * Returns the primary key of this sku inventory.
	 *
	 * @return the primary key of this sku inventory
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this sku inventory.
	 *
	 * @param primaryKey the primary key of this sku inventory
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the sku of this sku inventory.
	 *
	 * @return the sku of this sku inventory
	 */
	@AutoEscape
	public String getSku();

	/**
	 * Sets the sku of this sku inventory.
	 *
	 * @param sku the sku of this sku inventory
	 */
	public void setSku(String sku);

	/**
	 * Returns the group ID of this sku inventory.
	 *
	 * @return the group ID of this sku inventory
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this sku inventory.
	 *
	 * @param groupId the group ID of this sku inventory
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this sku inventory.
	 *
	 * @return the company ID of this sku inventory
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this sku inventory.
	 *
	 * @param companyId the company ID of this sku inventory
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the quantity of this sku inventory.
	 *
	 * @return the quantity of this sku inventory
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this sku inventory.
	 *
	 * @param quantity the quantity of this sku inventory
	 */
	public void setQuantity(int quantity);

	/**
	 * Returns the booked quantity of this sku inventory.
	 *
	 * @return the booked quantity of this sku inventory
	 */
	public int getBookedQuantity();

	/**
	 * Sets the booked quantity of this sku inventory.
	 *
	 * @param bookedQuantity the booked quantity of this sku inventory
	 */
	public void setBookedQuantity(int bookedQuantity);

	/**
	 * Returns the reserved quantity of this sku inventory.
	 *
	 * @return the reserved quantity of this sku inventory
	 */
	public int getReservedQuantity();

	/**
	 * Sets the reserved quantity of this sku inventory.
	 *
	 * @param reservedQuantity the reserved quantity of this sku inventory
	 */
	public void setReservedQuantity(int reservedQuantity);

	/**
	 * Returns the available quantity of this sku inventory.
	 *
	 * @return the available quantity of this sku inventory
	 */
	public int getAvailableQuantity();

	/**
	 * Sets the available quantity of this sku inventory.
	 *
	 * @param availableQuantity the available quantity of this sku inventory
	 */
	public void setAvailableQuantity(int availableQuantity);

}