/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.liferaybotics.model.impl;

import com.liferay.liferaybotics.model.SkuSales;
import com.liferay.liferaybotics.model.SkuSalesModel;
import com.liferay.liferaybotics.model.SkuSalesSoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SkuSales service. Represents a row in the &quot;Liferaybotics_SkuSales&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SkuSalesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SkuSalesImpl}.
 * </p>
 *
 * @author Peter Richards
 * @see SkuSalesImpl
 * @generated
 */
@JSON(strict = true)
public class SkuSalesModelImpl
	extends BaseModelImpl<SkuSales> implements SkuSalesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sku sales model instance should use the <code>SkuSales</code> interface instead.
	 */
	public static final String TABLE_NAME = "Liferaybotics_SkuSales";

	public static final Object[][] TABLE_COLUMNS = {
		{"sku", Types.VARCHAR}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"quantitySold", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("sku", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("quantitySold", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Liferaybotics_SkuSales (sku VARCHAR(75) not null primary key,groupId LONG,companyId LONG,quantitySold INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table Liferaybotics_SkuSales";

	public static final String ORDER_BY_JPQL = " ORDER BY skuSales.sku ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Liferaybotics_SkuSales.sku ASC";

	public static final String DATA_SOURCE = "noDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SKU_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static SkuSales toModel(SkuSalesSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SkuSales model = new SkuSalesImpl();

		model.setSku(soapModel.getSku());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setQuantitySold(soapModel.getQuantitySold());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<SkuSales> toModels(SkuSalesSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SkuSales> models = new ArrayList<SkuSales>(soapModels.length);

		for (SkuSalesSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SkuSalesModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _sku;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setSku(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _sku;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return SkuSales.class;
	}

	@Override
	public String getModelClassName() {
		return SkuSales.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SkuSales, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SkuSales, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SkuSales, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((SkuSales)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SkuSales, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SkuSales, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SkuSales)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SkuSales, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SkuSales, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, SkuSales>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			SkuSales.class.getClassLoader(), SkuSales.class,
			ModelWrapper.class);

		try {
			Constructor<SkuSales> constructor =
				(Constructor<SkuSales>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<SkuSales, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SkuSales, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SkuSales, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<SkuSales, Object>>();
		Map<String, BiConsumer<SkuSales, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SkuSales, ?>>();

		attributeGetterFunctions.put("sku", SkuSales::getSku);
		attributeSetterBiConsumers.put(
			"sku", (BiConsumer<SkuSales, String>)SkuSales::setSku);
		attributeGetterFunctions.put("groupId", SkuSales::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<SkuSales, Long>)SkuSales::setGroupId);
		attributeGetterFunctions.put("companyId", SkuSales::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<SkuSales, Long>)SkuSales::setCompanyId);
		attributeGetterFunctions.put("quantitySold", SkuSales::getQuantitySold);
		attributeSetterBiConsumers.put(
			"quantitySold",
			(BiConsumer<SkuSales, Integer>)SkuSales::setQuantitySold);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getSku() {
		if (_sku == null) {
			return "";
		}
		else {
			return _sku;
		}
	}

	@Override
	public void setSku(String sku) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sku = sku;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public int getQuantitySold() {
		return _quantitySold;
	}

	@Override
	public void setQuantitySold(int quantitySold) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_quantitySold = quantitySold;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public SkuSales toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SkuSales>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SkuSalesImpl skuSalesImpl = new SkuSalesImpl();

		skuSalesImpl.setSku(getSku());
		skuSalesImpl.setGroupId(getGroupId());
		skuSalesImpl.setCompanyId(getCompanyId());
		skuSalesImpl.setQuantitySold(getQuantitySold());

		skuSalesImpl.resetOriginalValues();

		return skuSalesImpl;
	}

	@Override
	public SkuSales cloneWithOriginalValues() {
		SkuSalesImpl skuSalesImpl = new SkuSalesImpl();

		skuSalesImpl.setSku(this.<String>getColumnOriginalValue("sku"));
		skuSalesImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		skuSalesImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		skuSalesImpl.setQuantitySold(
			this.<Integer>getColumnOriginalValue("quantitySold"));

		return skuSalesImpl;
	}

	@Override
	public int compareTo(SkuSales skuSales) {
		String primaryKey = skuSales.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SkuSales)) {
			return false;
		}

		SkuSales skuSales = (SkuSales)object;

		String primaryKey = skuSales.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SkuSales> toCacheModel() {
		SkuSalesCacheModel skuSalesCacheModel = new SkuSalesCacheModel();

		skuSalesCacheModel.sku = getSku();

		String sku = skuSalesCacheModel.sku;

		if ((sku != null) && (sku.length() == 0)) {
			skuSalesCacheModel.sku = null;
		}

		skuSalesCacheModel.groupId = getGroupId();

		skuSalesCacheModel.companyId = getCompanyId();

		skuSalesCacheModel.quantitySold = getQuantitySold();

		return skuSalesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SkuSales, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SkuSales, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SkuSales, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SkuSales)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SkuSales, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SkuSales, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SkuSales, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SkuSales)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SkuSales>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _sku;
	private long _groupId;
	private long _companyId;
	private int _quantitySold;

	public <T> T getColumnValue(String columnName) {
		Function<SkuSales, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SkuSales)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("sku", _sku);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("quantitySold", _quantitySold);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("sku", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("quantitySold", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SkuSales _escapedModel;

}